/** I am doing this coding with a lot of difficulty, please don't post it yourself¯\_(ツ)_/¯ **/
module.exports.config = {
  name: "tiktok",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Md Nazrul Islam",
  description: "HOT VEDIO",
  commandCategory: "Hình ảnh",
  usages: "sad vedio",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
};

module.exports.run = async({api,event,args,client,Users,Threads,__GLOBAL,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
   var hi = ["- 🥀THIS🥀 VIDEO MADE BY SHAAN KHAN K🥀-💓--"];
  var know = hi[Math.floor(Math.random() * hi.length)];
  var link = [
   "https://i.imgur.com/kiWgfN9.mp4",
    "https://i.imgur.com/pwEXNdW.mp4",
    "https://i.imgur.com/P9cisKC.mp4",
    "https://i.imgur.com/4Kzp6YS.mp4",
    "https://i.imgur.com/2QPYmsV.mp4",
    "https://i.imgur.com/9hFZq8C.mp4",
    "https://i.imgur.com/Wzn2bCW.mp4",
    "https://i.imgur.com/TS7ZS1r.mp4",
    "https://i.imgur.com/kxGbsHO.mp4",
    "https://i.imgur.com/cLGEG0i.mp4",
    "https://i.imgur.com/WaT6RbV.mp4",
    "https://i.imgur.com/rimJx5g.mp4",
    "https://i.imgur.com/VvRmk2N.mp4",
    "https://i.imgur.com/CwyJD8e.mp4",
    "https://i.imgur.com/Drn0JeT.mp4",
    "https://i.imgur.com/85p6Xbm.mp4",
    "https://i.imgur.com/uEa9WkK.mp4",
    "https://i.imgur.com/l5mJPL7.mp4",
    "https://i.imgur.com/oFoP7WO.mp4",
    "https://i.imgur.com/3VvdWnF.mp4",
    "https://i.imgur.com/dXhuOEJ.mp4",
    "https://i.imgur.com/S9sGpyg.mp4",
    "https://i.imgur.com/Zih1E6I.mp4",
    "https://i.imgur.com/9mqeHb8.mp4",
    "https://i.imgur.com/fjdNYaZ.mp4",
    "https://i.imgur.com/D9yoPwo.mp4",
    "https://i.imgur.com/HT2W1rT.mp4",
    "https://i.imgur.com/5yMCTj7.mp4",
    "https://i.imgur.com/KIWOxsh.mp4",
    "https://i.imgur.com/Cq2Hf1l.mp4",
    "https://i.imgur.com/smQZBem.mp4",
    "https://i.imgur.com/VPdRj9t.mp4",
    "https://i.imgur.com/EmOAnOf.mp4",
    "https://i.imgur.com/IPzQLtm.mp4",
    "https://i.imgur.com/xIn1xwH.mp4",
    "https://i.imgur.com/HaPtJWy.mp4",
    "https://i.imgur.com/hHuHCit.mp4",
    "https://i.imgur.com/ymSQI6K.mp4",
    "https://i.imgur.com/2xg8T3z.mp4",
    "https://i.imgur.com/pj2GTq1.mp4",
"https://i.imgur.com/k8Nk0hk.mp4",
"https://i.imgur.com/FaIml7d.mp4",
"https://i.imgur.com/OkRgdhx.mp4",
"https://i.imgur.com/Fuqw85P.mp4",
"https://i.imgur.com/YSePMXk.mp4",
"https://i.imgur.com/NulbpFV.mp4",
"https://i.imgur.com/mvLoOEO.mp4",
"https://i.imgur.com/9nMyQSa.mp4",
"https://i.imgur.com/AS3w3XL.mp4",
"https://i.imgur.com/le8LPPr.mp4",
"https://i.imgur.com/VEW8i5R.mp4",
"https://i.imgur.com/RZxOOAs.mp4",
"https://i.imgur.com/TgqMPYe.mp4",
"https://i.imgur.com/Pu8RrPM.mp4",
"https://i.imgur.com/wODFzYz.mp4",
"https://i.imgur.com/qSkqeyy.mp4",
"https://i.imgur.com/b7SLRM3.mp4",
"https://i.imgur.com/rZmJywH.mp4",
"https://i.imgur.com/09Rj19K.mp4",
"https://i.imgur.com/yhR6FZ6.mp4",
"https://i.imgur.com/uQmqHiN.mp4",
"https://i.imgur.com/wObBUEl.mp4",
"https://i.imgur.com/vHHxvqs.mp4",
"https://i.imgur.com/iBE1tSd.mp4",
"https://i.imgur.com/Nyk31E1.mp4",
"https://i.imgur.com/j4y9n8i.mp4",
"https://i.imgur.com/nLfS0yV.mp4",
"https://i.imgur.com/c4KjwW2.mp4",
"https://i.imgur.com/AIdtot3.mp4",
"https://i.imgur.com/wotdbfx.mp4",
"https://i.imgur.com/sP9oOls.mp4",
"https://i.imgur.com/pAQsyQR.mp4",
"https://i.imgur.com/NZKU2cj.mp4",
"https://i.imgur.com/yFq4SJH.mp4",
"https://i.imgur.com/wBKwnIP.mp4",
"https://i.imgur.com/z5ZmOWD.mp4",
"https://i.imgur.com/RzZZmjX.mp4",
"https://i.imgur.com/aVXg9xA.mp4",
"https://i.imgur.com/eMfWK8B.mp4",
"https://i.imgur.com/i6a99Ip.mp4",
"https://i.imgur.com/mC9QWRk.mp4",
"https://i.imgur.com/b6T2TQ4.mp4",
"https://i.imgur.com/FrDJ8ML.mp4",
    
];
     var callback = () => api.sendMessage({body:`「 ${know} 」`,attachment: fs.createReadStream(__dirname + "/cache/15.mp4")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/15.mp4"));    
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/15.mp4")).on("close",() => callback());
   };
